// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = (Integer.parseInt(args[0]));
		int above = 0;
		int below = 0;
		for (int i = 0; i < n; i++) {
			double random = Math.random();
			if (random > 0.5 ){
				above++;
			}
			else {
				below++;
			}
		}
		if (below == 0){
			System.out.println("> 0.5 " + above + " times");
			System.out.println("<= 0.5 " + below + " times");
		}
		else{
			System.out.println("> 0.5 " + above + " times");
			System.out.println("<= 0.5 " + below + " times");
			System.out.println("Ratio: " + (double)above/below);
		}

	}
}
